### ISSUE TITLE
[Suggestion] Ability to calculate a transfer angle bigger than 360°

### ISSUE THREAD

**Issue by fibonatic** [alexmoon/ksp#6]
Since if you would be able to launch at an ascending or descending node but will not encounter the target planet right away, but on the second or third time around you would you can save quite some fuel from not having to change your inclination.

**Comment by alexmoon** [comment]
Multi-revolution transfers is an interesting problem, so I've gone ahead and added it. You won't see them unless you zoom out or drag the plot down to see the longer transfers. Also, they will not appear on mid-course plane change plots. I've also limited the maximum number of revolutions to 10 for performance reasons.

Multi-revolution transfers tend to look a little weird, due to constraints on when the transfer is possible and the number of solutions that exist (for each additional orbit, another two solutions become possible). Most of the time it doesn't save you very much delta-v, but there are exceptions (like a 2.5 revolution transfer to Moho around day 128 for 4048m/s after insertion).
